version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Port for application connections
      - "15672:15672" # Port for the web management UI
    networks:
      - ms-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  service-registry:
    build:
      context: ./serviceregistry
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/apps/"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ms-net

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8765:8765"
    depends_on:
      service-registry:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    networks:
      - ms-net

  user-service:
    build:
      context: ./userservice
    ports:
      - "8081:8080"
    depends_on:
      service-registry:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - ms-net

  project-service:
    build:
      context: ./projectservice
    ports:
      - "8082:8080"
    depends_on:
      service-registry:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    networks:
      - ms-net

networks:
  ms-net:
    driver: bridge
