spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: notification-ws
          uri: lb:ws://notificationservice
          predicates:
            - Path=/ws/notifications/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "http://localhost:*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

server:
  port: 8765

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/


jwt:
  secret: ${SECRET_KEY}
