spring:
  application:
    name: notificationservice

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
logging:
  level:
    com:
      example: DEBUG
server:
  port: 8084

task:
  url: ${TASK_URL}

project:
  url: ${PROJECT_URL}

sprint:
  url: ${SPRINT_URL}

jwt:
  secret: ${SECRET_KEY}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
