spring:
  application:
    name: discussionservice
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER}
      database: ${MONGODB_DATABASE}
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/